version: 2.1

#defaults: &defaults
#  working_directory: ~/amorphic

executors:
  base_exec:
    #    <<: *defaults
#    working_directory: ~/amorphic
    docker:
      - image: circleci/node:lts
        environment:
          port: 3001
          dbUser: postgres
          dbName: test
          mongoHost: localhost
          logLevel: info
      - image: circleci/mongo:4.2.7
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  setup:
    executor: base_exec
    steps:
      - checkout
      - run:
          name: Install lerna
          command: npm install
      - run:
          name: Install all modules
          command: npm run setup

      # build for all packages
      - run:
          name: Build packages
          command: npm run build

      - save_cache:
          key: components-{{.Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  #      - save_cache:
  #          key: deps-{{ checksum "package-lock.json" }}
  #          paths:
  #            - node_modules

  all_tests:
    executor: base_exec
    steps:
      - restore_cache:
          key: components-{{.Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
      #      - restore_cache:
      #          key: deps-{{ checksum "package-lock.json" }}
      #          paths:
      #            - node_modules


      # run javascript tests - Supertype!
      - run:
          name: Supertype JS Tests
          command: npm run test:supertype

      # run typescript tests - Supertype!
      - run:
          name: Supertype TS Tests
          command: npm run test:ts:supertype

      # run javascript tests - Semotus!
      - run:
          name: Semotus JS Tests
          command: npm run test:semotus

      # run typescript tests - Semotus!
      - run:
          name: Semotus TS Tests
          command: npm run test:ts:semotus


      # run javascript tests - Amorphic!
      - run:
          name: Amorphic JS Tests
          command: npm run test:amorphic

      # run typescript tests - Amorphic!
      - run:
          name: Amorphic TS Tests
          command: npm run test:ts:amorphic

      #      # run javascript tests - Persistor!
      - run:
          name: Persistor JS Tests
          command: npm run test:persistor

      # run typescript tests - Persistor!
      - run:
          name: Persistor TS Tests
          command: npm run test:ts:persistor

#      # run all js tests
#      - run:
#          name: All Tests
#          command: npm run test
#
#      # run all ts tests
#      - run:
#          name: All Tests
#          command: npm run test:ts

workflows:
  version: 2
  amorphic:
    jobs:
      - setup
      - all_tests:
          requires:
            - setup