version: 2.1

#defaults: &defaults
#  working_directory: ~/amorphic

executors:
  base_exec:
    #    <<: *defaults
    working_directory: ~/amorphic
    docker:
      - image: circleci/node:lts
        environment:
          port: 3001
          dbUser: postgres
          dbName: test
          mongoHost: localhost
          logLevel: info
      - image: circleci/mongo:4.2.7
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  checkout:
    executor: base_exec
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows
  install:
    executor: base_exec
    steps:
      # Restore checkout dependencies
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Restore cache from package-lock.json
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "package-lock.json" }}
      - run:
          name: Install lerna
          command: npm install
      - run:
          name: Install all modules
          command: npm run setup

      # @TODO Make this simpler without the repetitive save_caaches
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/amorphic/node_modules
          key: v1-deps-amorphic-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/semotus/node_modules
          key: v1-deps-semotus-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/persistor/node_modules
          key: v1-deps-persistor-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/supertype/node_modules
          key: v1-deps-supertype-{{ checksum "package-lock.json" }}

  build:
    executor: base_exec
    steps:
      - restore_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - restore_cache:
          paths:
            - components/amorphic/node_modules
          key: v1-deps-amorphic-{{ checksum "package-lock.json" }}
      - restore_cache:
          paths:
            - components/semotus/node_modules
          key: v1-deps-semotus-{{ checksum "package-lock.json" }}
      - restore_cache:
          paths:
            - components/persistor/node_modules
          key: v1-deps-persistor-{{ checksum "package-lock.json" }}
      - restore_cache:
          paths:
            - components/supertype/node_modules
          key: v1-deps-supertype-{{ checksum "package-lock.json" }}

      # build for all packages
      - run:
          name: Build packages
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/amorphic/node_modules
          key: v1-deps-amorphic-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/semotus/node_modules
          key: v1-deps-semotus-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/persistor/node_modules
          key: v1-deps-persistor-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - components/supertype/node_modules
          key: v1-deps-supertype-{{ checksum "package-lock.json" }}

  all_tests:
    executor: base_exec
    steps:

      # run javascript tests - Supertype!
      - run:
          name: Supertype JS Tests
          command: npm run test:supertype

      # run typescript tests - Supertype!
      - run:
          name: Supertype TS Tests
          command: npm run test:ts:supertype

      # run javascript tests - Semotus!
      - run:
          name: Semotus JS Tests
          command: npm run test:semotus

      # run typescript tests - Semotus!
      - run:
          name: Semotus TS Tests
          command: npm run test:ts:semotus


      # run javascript tests - Amorphic!
      - run:
          name: Amorphic JS Tests
          command: npm run test:amorphic

      # run typescript tests - Amorphic!
      - run:
          name: Amorphic TS Tests
          command: npm run test:ts:amorphic

      #      # run javascript tests - Persistor!
      - run:
          name: Persistor JS Tests
          command: npm run test:persistor

      # run typescript tests - Persistor!
      - run:
          name: Persistor TS Tests
          command: npm run test:ts:persistor

#      # run all js tests
#      - run:
#          name: All Tests
#          command: npm run test
#
#      # run all ts tests
#      - run:
#          name: All Tests
#          command: npm run test:ts

workflows:
  version: 2
  checkout:
    jobs:
      - checkout
  install:
    jobs:
      - install
  build:
    jobs:
      - build
  test:
    jobs:
      #      - supertype_tests:
      #          requires:
      #            - build
      #      - semotus_tests:
      #          requires:
      #            - build
      #      - amorphic_tests:
      #          requires:
      #            - build
      #      - persistor_tests:
      #          requires:
      #            - build
      - all_tests