version: '2'
services:
  postgres:
    image: circleci/postgres:latest
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=persistor
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=trust
  # uncomment to save data between tests
  #    volumes:
  #      - ./.postgres:/var/lib/postgresql/data
  mongo:
    image: circleci/mongo:3.4
    ports:
      - 27017
  # uncomment to save data between tests
  #    volumes:
  #      - ./.mongo:/data/db
  persistor:
    build:
      context: .
    depends_on:
      - mongo
      - postgres
    environment:
      - logLevel=info
    volumes:
      - ./:/app
    env_file:
      - ./test.env
    command: ./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh mongo:27017 -- npm run test
